apiVersion: v1
kind: ConfigMap
metadata:
  name: sentiment-config
  namespace: sentiment-analysis
data:
  KAFKA_BROKERS: "kafka-service:9092"
  DB_HOST: "mariadb-service"
  DB_PORT: "3306"
  DB_NAME: "sentiment_db"
  MEMCACHED_HOST: "memcached-service:11211"
  SPARK_MASTER_URL: "spark://spark-master-service:7077"
  ZOOKEEPER_CONNECT: "zookeeper-service:2181"
